import Header from "@/components/Header";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ScrollObserver } from "@/contexts/ScrollContext";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "700"] });
// const bebas = Bebas_Neue({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ScrollObserver>
      <html lang="en">
        <body className={`${poppins.className}  scroll-smooth antialiased`}>
          <Providers>
            <Header />
            {children}
          </Providers>
        </body>
      </html>
    </ScrollObserver>
  );
}
